### ISSUE TITLE
Feature request: consistent hashing for tensors

### ISSUE THREAD

**Issue by jjtolton** [cnuernber/dtype-next#10]
Usecase:

In libapl-clj, until zero-copy is established and in situations where zero-copy cannot be used, I need to to do bookkeeping on tensors and values that engage in interop with libapl-clj.  The goal is to provide complete interoperability with dtype-next by using the tensor as the base datatype.  I will be hanging the hash value of the tensor and the hash value of the APL pointer on tensor object.  That way, if a downstream user manipulation results in a modified tensor, a simple hash check can validate if the hash of the new tensor is the same as the hash of the old tensor.  Then when libapl-clj functions are employed, libapl will update the APL pointer with the value of the new tensor and then update the hash values on the metadata.  

My current workaround that provides a consistent hash value:
```clojure
(hash (vec (dtype/->reader (tensor/->tensor [[1 2 3]
                                             [4 5 6]]))))
```

What would be preferable:
```clojure
(hash (tensor/->tensor [[1 2 3]
                        [4 5 6]]))
```

**Comment by cnuernber** [comment]
Hashing things like tensor can be pretty expensive but I understand the request.  A hash-by-value pathway for tensors would be interesting.

**Comment by cnuernber** [comment]
I think this isn't such a good idea.  What happens when there are floating point values that differ at some point?  Equals comparisons of floating point values usually involve an error threshold and aren't bit-exact so if, for instance, you run PCA twice on the same input and ask the the hash value, even though the tensor will look the same the hashed value may not be.

If you want to hash like that then I would suggest hashing the return value dtt/->jvm so the hash takes the structure of the data into account.

**Comment by cnuernber** [comment]
Use is the object identity as the hash value: `System.identityHashCode(object)`

**Comment by jjtolton** [comment]
Sounds good :) I wasn't sure if there was some sort of hashing shortcut that I was unaware of.  Happy to rock those out.
