### ISSUE TITLE
Support for library interface that accepts pass-by-value struct arguments and return types

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#69]
It doesn't seem like `tech.v3.datatype.ffi/define-library-interface` supports function arguments or return types that are structs. Is there a way to do that or a workaround?

**Comment by cnuernber** [comment]
Pass-by-value requires considerable work for all the bindings - you have to define jna structs that derive from a particular base class for instance and then for the java 17+ FFI system there are similar constraints.  

I would love to support pass-by-value for structs but that as I said takes real work.  Totally doable as the underlying libffi definitely supports it.

**Comment by phronmophobic** [comment]
👍 Sounds good. I might try to look into it if I get some time. 

I don't know if you would be interested, but in my head, having serialize/deserialize setup like [coffi](https://github.com/IGJoshua/coffi) seems useful, but I haven't actually tried it. Maybe I'll give coffi a try for this particular use case, but my other libraries rely on dtype-next's support for multiple environments (eg. jna, graalvm). Maybe there's a way to generalize coffi's serialization/deserialization.

**Comment by cnuernber** [comment]
Those are two completely different things.  

Coffi as far as I can tell also does not support function arguments that take structs passed by value.

dtype-next has excellent [support for structs](https://cnuernber.github.io/dtype-next/tech.v3.datatype.struct.html) - including arrays of structs which you can then use as a dataset.  A struct definition from dtype-next looks just like a map - have you looked at the struct namespace?  I thought you had because I thought we had talked about how you can use the output of clang to produce a struct definition.  This is something coffi doesn't have - so if your struct is an involved struct coming from a c library then you really should be using [clang to define the struct and taking its output to use with dtype-next](https://cnuernber.github.io/dtype-next/tech.v3.datatype.ffi.html).

I don't see the need for serialization/deserialization.  You can access the struct just like a map.

All this is independent of passing structs by value.  You can always pass an receive them by pointer and there are functions that transform a pointer to a struct and back.

**Comment by cnuernber** [comment]
Your question I guess is ambiguous as C has two different ways of passing structs.  No one supports pass-by-value as far as I can tell, everyone supports structs passed by pointer (or `reference` in c++ nomenclature).

**Comment by phronmophobic** [comment]
> No one supports pass-by-value as far as I can tell, everyone supports structs passed by pointer (or reference in c++ nomenclature).

JNA has support https://github.com/java-native-access/jna#features
> Structure and Union arguments/return values, by reference and by value

------- 

It's possible that I'm using the wrong jargon, but as far as I can tell, coffi does support pass value:

```c
typedef struct S1 {
    long long l;
    int i;
} S1;


extern long long add_struct(S1 s){
    return s.l + s.i;
}

```

```clojure
(defalias ::S1
  [::mem/struct
   [[:l ::mem/long]
    [:i ::mem/int]]])

(defcfn add_struct
  "doc string"
  add_struct [::S1] ::mem/long)


> (add_struct {:l 32
               :i 10})
42

```

**Comment by cnuernber** [comment]
I was wrong!  -  coffi then does support struct pass-by-value.  JNA always did but you have to create a custom struct derived from their passByValue marker class.  By no one I meant dtype-next and coffi.

**Comment by phronmophobic** [comment]
> dtype-next has excellent [support for structs](https://cnuernber.github.io/dtype-next/tech.v3.datatype.struct.html) - including arrays of structs which you can then use as a dataset. A struct definition from dtype-next looks just like a map - have you looked at the struct namespace? I thought you had because I thought we had talked about how you can use the output of clang to produce a struct definition. This is something coffi doesn't have - so if your struct is an involved struct coming from a c library then you really should be using [clang to define the struct and taking its output to use with dtype-next](https://cnuernber.github.io/dtype-next/tech.v3.datatype.ffi.html).

Yes, I've used the struct support with avclj. It's great! I'm currently writing a wrapper for libclang which does use structs for function args and return values (like [CXCursor](https://github.com/llvm/llvm-project/blob/476a497f729a408ba436f75fc50a41254ce65bc8/clang/include/clang-c/Index.h#L2097))

The goal is use libclang to streamline writing wrappers for c libraries. My current approach is to use python's wrapper for libclang to bootstrap the wrapper for libclang via libpython-clj (another wonderful project of yours 🙏 ). After I bootstrap, I can use then use the wrapper to improve itself.

**Comment by cnuernber** [comment]
OK, well then coffi does support pass by value and getting that support to work in dtype-next across jna would be something that takes work.

JNA is the only system so far that can run python that I have found.  Specifically extensions such as numpy which expect to find the source library's symbols (in this case libpython) fail to load when loaded via the java FFI system in java 17,18, etc.  I haven't tracked this down very far but I think it has to do with how java binds shared library access to class loaders; it doesn't allow the library to add its symbols to the process-wide symbol table.  

This is unfortunate because the built in FFI systems of java17+ really are quite a bit faster *but* if your problem comes down to very granular cross-language function calls I would say you should redefine your problem.  Even with that libpython-clj is quite a bit faster than the other java python systems because the overall speed of the bindings is has more to do with specifically how you marshall function arguments back and forth which involves many C calls and potentially allocations.

**Comment by phronmophobic** [comment]
Just pushed a beta version of my libclang wrapper, [clong](https://github.com/phronmophobic/clong). It includes some class generation to make it easier to pass pass structs by value via jna. It should also streamline generating api specifications from header files that can be passed to `dt-ffi/define-library-interface`.

When I get some time, I'll try to see what steps would be required to support pass-by-value structs in dtype-next.

**Comment by cnuernber** [comment]
That is great work!!

**Comment by cnuernber** [comment]
Jna is more flexible and robust for finding libraries.  It would probably not require a java-library-path change and if it did you could do it at runtime.

**Comment by phronmophobic** [comment]
> Jna is more flexible and robust for finding libraries. It would probably not require a java-library-path change and if it did you could do it at runtime.
That's a good point. Ideally, it would be nice to have jars that include native dependencies. At some point, I'll probably get annoyed enough to write some github actions that automate that process.

**Comment by cnuernber** [comment]
Hmm - I think fat jars also introduce quite a lot of nontrivial issues such as build farms and os system library dependency issues.

I personally think Java went the exact wrong way with that direction.  You end up in ludicrous situations such as trying to package all of python, numpy, and tensorflow binary deps into a single library with a lot of dependency issues.  Or see the javacpp versions for cuda - one for each javacpp version and one for each cuda version.  You end up with a cartesian join of possible versions of all software.

**Comment by phronmophobic** [comment]
I wasn't thinking that clong would include libclang in its jar, but that libclang would be available on its own with a separate jar for each version/OS/architecture. Does that still suffer from the same problems? 

From a user perspective, it's nice to be able to include a library by just adding some deps to your `deps.edn` file. It's not so bad if you can get the native dependencies through your package manager. libclang is annoying because there isn't a package in macports that offers it (afaik).

**Comment by cnuernber** [comment]
It suffers from os library dependency issues but of course I use Linux and ubuntu certainly has Clang and various flavors of linux have different os libraries.

I didn't realize that macports didn't offer libclang - that is also annoying.

**Comment by cnuernber** [comment]
@phronmophobic - javacpp has clang - and a c++ parser that outputs their library specifications - and a build farm that outputs fat jars for lots of systems.

Even if you don't want their java api you could simply use them for the fat jars.

**Comment by phronmophobic** [comment]
Just spent a bit of time
going down the javacpp rabbit hole. Lots of interesting stuff. Thanks for the pointer! 

I’ll definitely have to try seeing if it’s possible to use their dep to pull in native deps. I’ll also have to ponder if there’s other good ideas I can possibly pilfer as well.

**Comment by phronmophobic** [comment]
So many cool libraries here, https://github.com/bytedeco/javacpp-presets including llvm and ffmpeg. Just adding the dependency and loading the class doesn't put the native lib where JNA can find it, but there's probably a way to make it work.

**Comment by cnuernber** [comment]
I think I noticed verbose logging - Turn on verbose logging - there used to be a variable and that outputs where he decompresses the shared library - it’s /temp or equivalent not on the system path but discoverable or potentially predictable
